### ISSUE TITLE
Feature request: Davies-Jones calculation for WBT

### ISSUE THREAD

**Issue by C-H-Simpson** [ecmwf-projects/thermofeel#13]
In Buzan et al. 2015, the authors note a big difference between the WBT calculation from Stull 2011 and Davies-Jones 2008, and recommend using Davies-Jones 2008. I notice this module has the Stull calculation. Can we have the Davies-Jones calculation too?

Buzan, J.R., Oleson, K. and Huber, M., 2015. Implementation and comparison of a suite of heat stress metrics within the Community Land Model version 4.5. Geoscientific Model Development, 8(2), pp.151-170. 
Davies-Jones, R.: An efficient and accurate method for computing the wet-bulb temperature along pseudoadiabats, Mon. Weather Rev., 136, 2764–2785, 2008
Stull, R.: Wet-bulb temperature from relative humidity and air temperature, J. Appl. Meteorol. Climatol., 50, 2267–2269, 2011.

**Comment by chlobrim** [comment]
Hi Thank you for your suggestion- We plan to look into this and see if we can implement this method as an approach to Wet Bulb Temperature Calculation.  We have recently been testing the Liljegren Method (Point method) out in comparison to our Wet Bulb Globe Temperature too. We will update you soon.

**Comment by chlobrim** [comment]
Hi Charles,

In the latest 1.2.0 release of thermofeel we've implemented the Dunne et al., 2013 version of the Davies-Jones Wet Bulb Temperature. You can also make use of this in WBGT by using calculate_wbgt(t_k, mrt, va, td, p=None) and including a value for p for surface pressure (mbar). 

Dunne paper: https://www.nature.com/articles/nclimate1827#Sec2
 
Thanks Chloe
