### ISSUE TITLE
Some inconsistencies with the calculate_heat_index_adjusted function

### ISSUE THREAD

**Issue by TC25** [ecmwf-projects/thermofeel#15]
I have noticed some differences between the equations in the heat index function, as incorporated in this package, and the equations listed here: https://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml

adjustment2 should be:

adjustment2 = (rh[hi_filter1 and hi_filter4 and hi_filter5] - 85) /10* (
        (87 - t2m[hi_filter1 and hi_filter4 and hi_filter5]) / 5

[first term should be divided by 10]

and should be added to hi, not subtracted. 

adjustment1 should be:

adjustment1 = (
        (13 - rh[hi_filter1 and hi_filter2 and hi_filter3])
        / 4
        * np.sqrt(
            17 - np.abs(t2m[hi_filter1 and hi_filter2 and hi_filter3] - 95) / 17
        )

[95 instead of 0.95]

Additionally, hi_filter6 should be for hi<80 (or, in practice, the average of the simpler formulation of hi and t2m being less than 80 degree F), not for only t2m<80. 

Let me know if I am missing something or if you are pulling the equations from a different source. 

Regards,
TC

**Comment by chlobrim** [comment]
Hi TC,
Thanks for your report. We are looking into it. 

Kind Regards,
Chloe

**Comment by TC25** [comment]
For reference, here is the function I have been using (takes Temp in degree C and relative humidity in % as inputs), partly based on your code:

# convert Fahrenheit to Celsius
def fahrenheit_to_celsius(tf):
    tc = (tf - 32) * 5 / 9
    return tc

def HI_NWS(Ta, RH):

    rh = np.array(RH)
    t2m = np.array(Ta*9/5 + 32)

    hi_init=0.5*(t2m+ 61.0+((t2m- 68.0) * 1.2)+ (rh*0.094))

    hiarray = [
    42.379,
    2.04901523,
    10.1433312,
    0.22475541,
    0.00683783,
    0.05481717,
    0.00122874,
    0.00085282,
    0.00000199,
    ]
    hi = (
    -hiarray[0]
    + hiarray[1] * t2m
    + hiarray[2] * rh
    - hiarray[3] * t2m * rh
    - hiarray[4] * t2m ** 2
    - hiarray[5] * rh ** 2
    + hiarray[6] * t2m ** 2 * rh
    + hiarray[7] * t2m * rh ** 2
    - hiarray[8] * t2m ** 2 * rh ** 2
    )

    if ((hi_init+t2m)/2<80):
        hi_final=hi_init
    elif ((t2m > 80)&(t2m < 112)&(rh <= 13)):
        adjustment1 =(
        (13 - rh)/4*np.sqrt(17 - np.abs(t2m - 95) / 17))
        hi_final=hi-adjustment1
    elif ((t2m > 80)&(t2m < 87)&(rh > 85)):
        adjustment2 = (rh - 85)/10 * ((87 - t2m) / 5)
        hi_final=hi+adjustment2
    else:
        hi_final=hi
    hi_final = fahrenheit_to_celsius(hi_final)
    return hi_final

**Comment by chlobrim** [comment]
Hi TC,

Thank you, I have made the changes in the develop branch. We are currently checking our unit testing and have taken the time to make some examples and look at our documentation. We aim to have a new release to fix our unfortunate typo this week. 

Best Wishes,
Chloe

**Comment by cascadet** [comment]
@chlobrim -

Regarding the issues @TC25 raised, is the package use for the [Climate extreme indices and heat stress indicators derived from CMIP6 global climate projections](https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-extreme-indices-cmip6?tab=overview) data release? And if so, will they be updated if errors are found in the package?

Thanks!

**Comment by chlobrim** [comment]
Hi Cascade,

The dataset you are referencing is separate to thermofeel. You can see their code for heat indices here: https://github.com/schwings-clemens/CDS_heat_stress_indicators/blob/main/calc_heat_stress_indicators.py#L171  

Heat index appears correct in this repo. However, WBGT and UTCI in this dataset are the indoor versions only as radiation is not considered.

We hope to have an update to heat index adjusted soon, as I said above we have also taken this opportunity to check other aspects of our library.

Hope that helps,
Best Wishes,
Chloe

**Comment by cascadet** [comment]
Thank you for the quick following up so quickly Chloe and for pointing me to the repo. Keep up the good work!

-Cascade

**Comment by tlmquintino** [comment]
@cascadet and @TC25 we have just released version **1.2.0**
That should fix this issue. Let us know if anything else remains to be addressed.

**Comment by tlmquintino** [comment]
Closing
