### ISSUE TITLE
Wind speed adjustment issue for Apparent Temperature calculation

### ISSUE THREAD

**Issue by hansukyang** [ecmwf-projects/thermofeel#18]
Hi - wondering if there is an error on the wind speed adjustment from 10m height to 2m?

On line 867 of thermofeel.py:

`va = va * 4.87 / np.log10(67.8 * 10 - 5.42)  # converting to 2m, ~1.2m wind speed`

Wondering if this should use a natural logarithm so it would look like:

`va = va * 4.87 / np.log(67.8 * 10 - 5.42)  # converting to 2m, ~1.2m wind speed`

Otherwise, the adjusted wind speed at lower height (2m) is always greater than the wind speed at 10m height. Thanks!

**Comment by chlobrim** [comment]
Hello - Sorry for the delayed response. You are correct the error was small when I checked, we've changed this in the thermofeel develop branch, for release shortly.

**Comment by hansukyang** [comment]
Fantastic - thanks for letting me know.
