### ISSUE TITLE
Potential errors in "calculate_wbt_dj" function

### ISSUE THREAD

**Issue by QINQINKONG** [ecmwf-projects/thermofeel#20]
Hi. I found a potential error in the function  "`calculate_wbt_dj`" . 
At line 694, the equation of saturation mixing ratio was falsely written as:
`wsat = 621.97 * esat * np.subtract(p, esat)`
where it should be:
`wsat = 621.97 * esat / np.subtract(p, esat)`

Also, this function was claimed to calculate wet bulb temperature using Davies-Jones approach. However, what it calculates is actually potential wet bulb temperature (e.q. 3.4 in Davies-Jones 2008). 
-Qin

**Comment by chlobrim** [comment]
Thank you, this methodology has been removed in the latest develop branch release, because it was an approximation. The full WBT_dj is something I'd like to add to thermofeel.
