### ISSUE TITLE
Mistake in calculate_wbgts

### ISSUE THREAD

**Issue by C-H-Simpson** [ecmwf-projects/thermofeel#21]
`calculate_wbgts` only takes a single input, when it should have two inputs. One input should be temperature, the other the vapour pressure in hPa. Instead, it currently calculates the saturation vapour pressure. The saturation vapour pressure is incorrectly labelled "rh".

**Comment by chlobrim** [comment]
Thank you. We've been updating the saturation vapour pressure method in the develop branch to that feeds into wbgts. This may be a parameter naming mishap, apologies for any confusion.
