### ISSUE TITLE
Issue with calculate_wbgts

### ISSUE THREAD

**Issue by cascadet** [ecmwf-projects/thermofeel#25]
It looks like `calculate_wbgts` from https://github.com/ecmwf-projects/thermofeel/blob/master/thermofeel/thermofeel.py has an error with it:

def calculate_wbgts(t2m):
>>>"""
wgbts - Wet Bulb Globe Temperature Simple
:param t2m: 2m temperature [K]
:param rh: relative humidity [pa]
https://link.springer.com/article/10.1007/s00484-011-0453-2
http://www.bom.gov.au/info/thermal_stress/#approximation
https://www.jstage.jst.go.jp/article/indhealth/50/4/50_MS1352/_pdf
returns Wet Bulb Globe Temperature [°C]
"""
rh = calculate_saturation_vapour_pressure(t2m)
rh = kPa_to_hPa(rh)
t2m = kelvin_to_celsius(t2m)
wbgts = 0.567 * t2m + 0.393 * rh + 3.38
return wbgts

The function documentation calls for rh as a parameter, but there is not an argument. Further, the function uses `calculate_saturation_vapour_pressure` but the object name is `rh`. 

Please advise and/or update as needed. This could potentially produce very strange results for those needing to estimate wet bulb globe temperatures.

Thanks!

**Comment by chlobrim** [comment]
Hello, Thank you. I will change the variable from rh this is a mishap in variable naming and a typo we missed. This uses Saturation vapour pressure in (Hpa). Apologies for any confusion.
