### ISSUE TITLE
calculate_mrt_from_bgt documentation specifies incorrect return unit

### ISSUE THREAD

**Issue by Jrodseth** [ecmwf-projects/thermofeel#26]
The documentation for [calculate_mrt_from_bgt](https://github.com/ecmwf-projects/thermofeel/blob/720911162ba1c614a20d6fd3c87dea9f554c5fd0/thermofeel/thermofeel.py#L788) specifies that the function returns mean radiant temperature in kelvin. However, the [last line of the function](https://github.com/ecmwf-projects/thermofeel/blob/720911162ba1c614a20d6fd3c87dea9f554c5fd0/thermofeel/thermofeel.py#L796) calls `kelvin_to_celsius` before returning.

Either the documentation should be changed to `returns mean radiant temperature [°C]` or the last line should be changed to `return mrtc2`

**Comment by chlobrim** [comment]
Hello - Thank you for spotting this oversight on our part this has been updated in the develop branch of thermofeel for implementation at a later date.
