### ISSUE TITLE
Mistakes in the heat index calculation

### ISSUE THREAD

**Issue by C-H-Simpson** [ecmwf-projects/thermofeel#28]
I've noticed some mistakes in the heat index calculation that make it unusable.

In calculate_heat_index_simplified(t2m, rh=None):
https://github.com/ecmwf-projects/thermofeel/blob/master/thermofeel/thermofeel.py#L864

```
if rh is None:
        rh = calculate_saturation_vapour_pressure(t2m)

    t2m = kelvin_to_celsius(t2m)
    rh = kPa_to_hPa(rh)
```

1. If no relative humidity is set then the saturation vapour pressure is calculated - this effectively assumes 100% humidity - why?
2. If no relative humidity is set then rh is overwritten by the vapour pressure, but if rh is supplied then rh is still a relative humidity.
3. The confusion is probably that rh should be the vapour pressure, not the the relative humidity. In fact, the docstring says its units are [Pa].
5. rh is then converted kPa_to_hPa which makes no sense if it is a relative humidity.
6. If a vapour pressure in Pa is given then the returned heat index is not correct (e.g. t2m=303.15, vap=2123 (~50% humidity at 30 C, correct answer 31) -> HI=326
7. If a vapour pressure is given in kPa, the answer returned is 57, which I still think is wrong.
8. The URL given in the docstring is not the source of the equations in this function.

In calculate_heat_index_adjusted
https://github.com/ecmwf-projects/thermofeel/blob/master/thermofeel/thermofeel.py#L904
The function simply does not run, e.g. with inputs t2m=303.15, td=291.5966398559667 the result is 

`TypeError: 'float' object is not subscriptable` at [line 981](https://github.com/ecmwf-projects/thermofeel/blob/master/thermofeel/thermofeel.py#L954)
Passing numpy arrays gives the same result.

It also doesn't make sense to me why the function asks for dewpoint temperature as an input but immediately converts to relative humidity and never uses the dewpoint temperature otherwise.

**Comment by C-H-Simpson** [comment]
There is a similar issue in calculate_apparent_temperature where it is not clear if rh is a pressure or a relative humidity.

**Comment by C-H-Simpson** [comment]
There is also a mistake in calculate_wbgts
https://github.com/ecmwf-projects/thermofeel/blob/master/thermofeel/thermofeel.py#L693

The vapor pressure is assumed to be the saturation vapor pressure, meaning that 100% humidity is assumed.

**Comment by chlobrim** [comment]
We are using the methodology from https://link.springer.com/article/10.1007/s00484-011-0453-2 of course there are multiple ways to calculate indices but we have checked and are happy - not accounting for bugs - with the methodology.
