### ISSUE TITLE
Relative humidity percentage Formula

### ISSUE THREAD

**Issue by jordihyds** [ecmwf-projects/thermofeel#3]
It seems that the RH percentage calculation is based on the US NWS formula (https://www.weather.gov/media/epz/wxcalc/vaporPressure.pdf), but this formula uses temperature in Celsius degrees while the code expects temperature in Kelvin. I thought that units in comment line may be wrong, but other parts of the code seem consistent with the use of Kelvin. Any expert could double check this formula?

**Comment by chlobrim** [comment]
Thank you for flagging this. Very sorry about that. We were meant to add a convert in calculate_relative_humidity_percent. This impacts 3 indexes the UTCI, NET and heat index adjusted. Overall the difference isn't very much. But we will release a new version by the end of the day.

**Comment by chlobrim** [comment]
@jordihyds we've updated the code and also used this opportunity to further refactor our tests and made them more robust.

**Comment by tlmquintino** [comment]
@jordihyds this is now fixed in release **1.0.1**
