### ISSUE TITLE
Error in calculate_bgt (line 744)

### ISSUE THREAD

**Issue by landriano1** [ecmwf-projects/thermofeel#30]
Hi! The calculate_bgt function accepts floats as inputs, but the numpy .clip function works on arrays (meaning that there is an attribute error when using this function).

Please let me know if I'm doing something wrong and the function is fine.

**Comment by chlobrim** [comment]
Hello - in our documentation we outline that intergers or floats should be wrapped as a numpy array. I hope that answers your question and helps fix this.
