### ISSUE TITLE
Why Gaussian numerical integration in calc cossza integrated?

### ISSUE THREAD

**Issue by jarataraj** [ecmwf-projects/thermofeel#31]
I am a little confused on why Gaussian numerical integration is used in `calculate_cos_solar_zenith_angle_integrated`. The [Hogan and Hirahara](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL066868) paper that details how to calculate the average cosine solar zenith angle recommends against it: 

>In both the Average and Average Daytime configurations shown in Figures [3](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL066868#grl53870-fig-0003) and [4](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015GL066868#grl53870-fig-0004), Earth curvature correction is applied after the averaging is performed to yield the value of $\mu_{0m}^{\prime}$ used in the radiation scheme. An alternative approach would be to do the averaging after accounting for Earth curvature. Unfortunately this cannot be done analytically, but we have tested this approach numerically using four-point Gaussian quadrature to compute an average value of $\mu_{0m}^{\prime}$ in the daytime part of the radiation time step. The flux errors are very similar to those of Average Daytime, while the stratospheric temperature errors are slightly worse over the poles (not shown). Thus, it appears that the extra computational expense of using numerical integration is not justified, so we recommend the use of an analytic average of the cosine of the solar zenith angle over the daytime part of the radiation time step, followed by Earth curvature correction.

My understanding of this is that they use Gaussian numerical integration in order to apply the corrections for earth's curvature *before* integrating to find the average cosine solar zenith angle. However, they found this to not make much difference and cause errors near the poles, and therefore recommend using the analytical integration method before applying the curvature correction:

Step 1: $\overline{\mu_{0m}} = \sin\delta\sin\phi + \frac{\cos\delta\cos\phi(\sin{h_{max}} - \sin{h_{min}})}{h_{max} - h_{min}}$

Step 2: $\mu_{0m}^{\prime} = \frac{H}{\sqrt{\mu_{0m}^2 + H (H + 2)} - \mu_{0m}}$

Why does thermofeel not use the analytical method (step 1 above)? From what I can tell, the curvature correction (step 2 above) is also not used. 

One other point of confusion: the Hogan and Hirahara article uses two different variables to represent cosine solar zenith angle: $\mu_{0m}$ and $\mu_{0}$. I am not sure I understand the difference between these and whether it affects the above question. 

Thank you for your help!

**Comment by chlobrim** [comment]
Hello please refer to our techmemo: https://www.ecmwf.int/en/elibrary/81295-calculating-cosine-solar-zenith-angle-thermal-comfort-indices this outlines the methodological choice. If you have specific questions about the Hogan and Hirahara manuscript we'd recommend e-mailing Robin Hogan.

**Comment by jarataraj** [comment]
Thank you!
