### ISSUE TITLE
MRT calculation breaking change with v1.3?

### ISSUE THREAD

**Issue by milankl** [ecmwf-projects/thermofeel#33]
Why is are the function arguments with v1.3
https://github.com/ecmwf-projects/thermofeel/blob/720911162ba1c614a20d6fd3c87dea9f554c5fd0/thermofeel/thermofeel.py#L361-L373
although it was 
https://github.com/ecmwf-projects/thermofeel/blob/e37aaed64235fbbef76f7cb6876f27e052438c46/thermofeel/thermofeel.py#L309-L321
before? Sorry, I cannot seem to find the documentation for this breaking change. Was it a bug before? The new argument `dsrp` seems to be used in some places where `fdir` was used before ...

**Comment by chlobrim** [comment]
Hello - No bug it's explained in this techmemo: https://www.ecmwf.int/en/elibrary/81295-calculating-cosine-solar-zenith-angle-thermal-comfort-indices Istar in MRT is an approximation of dsrp, this was updated for internal ECMWF processes. Sorry for any inconvinience.
