### ISSUE TITLE
Mean Radiant Temperature calculation

### ISSUE THREAD

**Issue by milankl** [ecmwf-projects/thermofeel#7]
Hey, when calculating the UTCI based on ECMWF's forecasts, with the typical temporal resolution (hourly for 0-90hours lead time, then 3-hourly until 144 hours, then 6-hourly until 360hours) I sometimes encounter unreasonably high mean radiant temperatures within the 6-hourly resolved data (which in this plot is directly reflected in the "sunshine" contribution in the bottom panel), that can also be seen in UTCI. For further examples check [this twitter bot](https://twitter.com/HeatForecast)

![image](https://user-images.githubusercontent.com/25530332/136184550-075b4d9f-fd89-4f3a-96c5-d4029a1a2747.png)

I call the functions from thermofeel as

```python
sec_in_step = [(timevec[i+1]-timevec[i]).seconds for i in range(len(timevec)-1)]
hrs_in_step = [(timevec[i+1]-timevec[i]).seconds/3600 for i in range(len(timevec)-1)]
    
# Solar zenith angle, integrated
cosszai = np.zeros(n_time_steps-1)

for i in range(1,n_time_steps):
    cosszai[i-1] = thermofeel.calculate_cos_solar_zenith_angle_integrated(lat=latlon[0],
                                            lon=latlon[1],
                                            y=timevec[i].year,
                                            m=timevec[i].month,
                                            d=timevec[i].day,
                                            h=timevec[i].hour,
                                            base=0,
                                            step=hrs_in_step[i-1])
        
# mean radiant temperature
mrt = np.zeros_like(t2m[:,1:])

for j in range(n_members):
    mrt[j,:] = thermofeel.calculate_mean_radiant_temperature(
                                         np.diff(ssrd[j,:])/sec_in_step,
                                         np.diff(ssr[j,:])/sec_in_step,
                                         np.diff(fdir[j,:])/sec_in_step,
                                         np.diff(strd[j,:])/sec_in_step,
                                         np.diff(strr[j,:])/sec_in_step,
                                         cosszai)
```
I was wondering whether you have an idea why the mean radiant temperature is going crazy, or how to test / fix this issue!

**Comment by tlmquintino** [comment]
We haven't merged this into master branch yet as we are still evaluating and validating the new method, but we are fairly confident with the solution in the development branch.

**Comment by tlmquintino** [comment]
In the new function signature for **calculate_cos_solar_zenith_angle_integrated** you will have to call it as:

`thermofeel.calculate_cos_solar_zenith_angle_integrated(lat=latlon[0],
                                            lon=latlon[1],
                                            y=timevec[i].year,
                                            m=timevec[i].month,
                                            d=timevec[i].day,
                                            h=timevec[i].hour,
                                            tbegin=72,
                                            tend=75)`

**Comment by tlmquintino** [comment]
We will close this issue as we believe this is now fixed. 
Feel free to reopen if you find it is not.

**Comment by milankl** [comment]
Using thermofeel v1.1.1 I'm now doing 

```python
forecast_hours = [int((timevec[i]-timevec[0]).total_seconds()/3600) for i in range(len(timevec))]
cosszai = np.zeros(n_time_steps-1)

for i in range(1,n_time_steps):
    cosszai[i-1] = thermofeel.calculate_cos_solar_zenith_angle_integrated(lat=latlon[0],
                                            lon=latlon[1],
                                            y=timevec[i].year,
                                            m=timevec[i].month,
                                            d=timevec[i].day,
                                            h=timevec[i].hour,
                                            tbegin=forecast_hours[i-1],
                                            tend=forecast_hours[i])
```
So the `ymdh` time is provided in UT, `latlon` defines the location, `tbegin` is the forecast lead time in hours from the previous time step, `tend` is the forecast lead time for `ymdh`. The `cosszai` array then looks reasonable I guess, `plt.plot(forecast_hours[1:],cosszai)`
![image](https://user-images.githubusercontent.com/25530332/142897761-8217bdb9-1051-4d99-b188-863202006de9.png)

However, the same graph as above now shows weird double peaks in UTCI and again suddenly jumps to unreasonably high values after 5 days. 
![image](https://user-images.githubusercontent.com/25530332/142900619-7ac3925c-c29c-4d1d-a45a-b0b2c1a6df4f.png)

which are due to peaks in MRT, `plt.plot(forecast_hours[1:],mrt[1,:])`
![image](https://user-images.githubusercontent.com/25530332/142901304-49d8ade9-b3ea-402b-b812-eef7e1790009.png)
Any clue what is going on here?

**Comment by milankl** [comment]
> Feel free to reopen if you find it is not.

I can't somehow?

**Comment by milankl** [comment]
https://github.com/ecmwf-projects/thermofeel/blob/48d7cf86758e056f4c300815a0c3fbfe725e0c27/thermofeel/thermofeel.py#L164-L174

Okay, I think I found the issue. `y, m, d, h` are the time from the forecast initialisation, not the actual time step the cosine is calculated for. Resulting figure looks also much better. Sorry for the confusion, to prevent this I'll create a PR with some additional info in the function comments
![image](https://user-images.githubusercontent.com/25530332/143620623-0702242e-2146-4760-bb7d-5d7c5b4e0b06.png)
